In [1]:
!pip3 install bidskit

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 3.2 MB 7.7 MB/s eta 0:00:01
  Using cached num2words-0.5.10-py3-none-any.whl (101 kB)
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [2]:
!bids-validator

/bin/bash: bids-validator: command not found


In [8]:
import numpy as np
np.eye(3)-(1/3)

array([[ 0.66666667, -0.33333333, -0.33333333],
       [-0.33333333,  0.66666667, -0.33333333],
       [-0.33333333, -0.33333333,  0.66666667]])

In [7]:
np.eye(2)-(1/2)

array([[ 0.5, -0.5],
       [-0.5,  0.5]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])